spring:
    datasource:
        url: "jdbc:mysql://localhost:3307/try_data"
        username: "root"
        password: ""
    sql:
        init:
            mode: always
            encoding: UTF-8
mybatis:
    configuration:
        map-underscore-to-camel-case: true